version: '3.7'
services:
  # edgeDataManager:
  #   image: edge_data_manager
  #   container_name: edge_data_manager
  #   build: 
  #     "./Edge/DataManager"
  #   depends_on:
  #     - mongodb
  # edgeIoTDevSim:
  #   image: edge_iot_dev_sim
  #   container_name: edge_iot_dev_sim
  #   mem_limit: 1g
  #   build: 
  #     "./Edge/IoTDevSim"
  #   blkio_config:
  #     weight: 300
  # edgeIoTSmartDev:
  #   image: edge_iot_smart_dev
  #   container_name: edge_iot_smart_dev
  #   build: 
  #     "./Edge/IoTSmartDev"
  edgePolygon:
    image: edge_polygon
    container_name: edge_polygon
    build: 
      "./Edge/Polygon"
    networks:
      - private_network
    ports:
      - "4001:4001"
      - "5001:5001"

networks:
      private_network:
        ipam:
          config:
            - subnet: 172.20.10.0/28
              gateway: 172.20.10.1

# networks:
#       private_network:
#         ipam:
#           config:
#             - subnet: 192.168.0.0/24
#               gateway: 192.168.0.1

# volumes:
#   mongo-db: