version: '3.7'
services:
  bootnode:
    hostname: bootnode
    image: bootnode_container
    container_name: bootnode
    tty: true
    build:
      context: ./Ethereum/Bootnode
    command: bootnode -nodekey /app/bootnode.key -addr host.docker.internal:30300
    ports:
      - "30300:30300"
    network_mode: host
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  node0:
    hostname: node0
    container_name: node0
    image: node0
    build:
      context: ./Ethereum/node0
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    tty: true
    depends_on:
      - bootnode
    command:
      --datadir /app/node0
      --syncmode full
      --port 30320
      --http
      --http.addr 192.168.0.11
      --http.port 8545
      --http.api eth,net,web3,miner,admin
      --bootnodes "enode://41a506356acaf6e5469f04847abf9e7efb1ff50805b1c4219580160c2aec0caf23b6aede3397e8939ee860b2bdb897b1caa3b0f1521a9fa3a95b23a6915b7a60@host.docker.internal:30300"
      --ipcpath /app/geth.ipc
      --authrpc.port 8546
      --http.corsdomain=*
      --mine
      --miner.etherbase 0x54e21c3a87f3f54b0ffb23b5951eaece7af62d9d
      --miner.gasprice 0
      --miner.gaslimit 999999999999
      --networkid=1214
      --unlock 0x54e21c3a87f3f54b0ffb23b5951eaece7af62d9d
      --password /app/password.txt
      --allow-insecure-unlock console
    ports:
      - "30320:30320"
      - "8545:8545"
    network_mode: host
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  edgePolygonNode0:
    image: edge_polygon_node0
    container_name: edge_polygon_node0
    tty: true
    depends_on:
      - bootnode
      - node0
    build: 
      "./Edge/Polygon"
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  requester_node:
    image: requester_node
    container_name: requester_node
    tty: true
    depends_on:
      - bootnode
      - node0
      - edgePolygonNode0
    build: 
      "./Requester/"
    volumes:
      - ~/Documents/EdgeEmulator/Case\ 4/Requester/:/app/Results
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
